[package]
name = "backend"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
api = {path = "./api"}
tokio = { version = "1.43.0", features = ["full"] }
axum = { version = "0.8.1", features = ["macros"] }
tower-http = { version = "0.6.2", features = ["cors"] }
