codecov:
  notify:
    wait_for_ci: false
coverage:
  status:
    project:
      default:
        target: 80%
        flags:
          - unittests
comment:
  layout: "header, files, footer"
  behavior: new
  require_changes: false
  require_head: false
  require_base: false
  hide_project_coverage: false