name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          submodules: recursive  # Enabling submodules fetching
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y racket
          rustup component add clippy
          cargo install cargo-sonar
          cargo install cargo-llvm-cov
      - name: Run clippy
        run: |
          cargo clippy --message-format json > clippy.json || true
      - name: Convert to sonar format
        run: |
          cargo sonar --clippy
      - name: Run LCOV
        run: |
          cargo llvm-cov --lcov --output-path lcov.info
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
